# Generated by Django 5.0.7 on 2024-08-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_remove_renthistory_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='renthistory',
            name='total_price',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
