# Generated by Django 5.0.7 on 2024-08-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_renthistory_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentroom',
            name='discount_active',
            field=models.BooleanField(default=False),
        ),
    ]
