# Generated by Django 5.0.8 on 2024-08-27 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0005_remove_rentroom_discount_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renthistory',
            name='total_price',
        ),
    ]
