# Generated by Django 5.0.8 on 2024-08-29 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0007_alter_renthistory_created_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='renthistory',
            name='total_price',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='renthistory',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='renthistory',
            name='paid_change',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rentroom',
            name='best_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rentroom',
            name='create',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rentroom',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rentroom',
            name='golden_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='rentroom',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rentroom',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rentroom',
            name='user',
            field=models.ForeignKey(limit_choices_to={'status': 'owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='user_rent', to=settings.AUTH_USER_MODEL),
        ),
    ]
