# Generated by Django 5.0.8 on 2024-08-29 14:11

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0009_remove_renthistory_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentroom',
            name='best_date',
            field=django_jalali.db.models.jDateField(),
        ),
        migrations.AlterField(
            model_name='rentroom',
            name='create',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rentroom',
            name='end_date',
            field=django_jalali.db.models.jDateField(),
        ),
        migrations.AlterField(
            model_name='rentroom',
            name='golden_date',
            field=django_jalali.db.models.jDateField(blank=True),
        ),
        migrations.AlterField(
            model_name='rentroom',
            name='start_date',
            field=django_jalali.db.models.jDateField(),
        ),
        migrations.AlterField(
            model_name='rentroom',
            name='update',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
    ]
