# Generated by Django 5.0.8 on 2024-08-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0010_alter_rentroom_best_date_alter_rentroom_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentroom',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
