# Generated by Django 5.0.8 on 2024-08-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0011_rentroom_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='renthistory',
            name='total_price',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
