# Generated by Django 5.0.8 on 2024-08-30 14:06

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0012_renthistory_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renthistory',
            name='created',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='renthistory',
            name='paid_change',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
    ]
