# Generated by Django 5.0.8 on 2024-08-30 14:58

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0013_alter_renthistory_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentroom',
            name='end_date',
            field=django_jalali.db.models.jDateTimeField(),
        ),
        migrations.AlterField(
            model_name='rentroom',
            name='start_date',
            field=django_jalali.db.models.jDateTimeField(),
        ),
    ]
