# Generated by Django 5.0.8 on 2024-08-30 15:00

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0014_alter_rentroom_end_date_alter_rentroom_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentroom',
            name='end_date',
            field=django_jalali.db.models.jDateField(),
        ),
        migrations.AlterField(
            model_name='rentroom',
            name='start_date',
            field=django_jalali.db.models.jDateField(),
        ),
    ]
