# Generated by Django 5.0.8 on 2024-09-01 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0017_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentroom',
            name='is_active',
        ),
    ]
